version: '3'

services:
  python :
      build: ./docker/python
      container_name: api_python
      tty : true
      ports :
        - 5000:5000
      volumes:
        - ./src/:/src
      networks:
        - api_network

  redis:
     image: redis
     container_name: api_redis
     ports :
      - 6379:6379
     networks:
        - api_network

  redis-commander:
    container_name: api_rediscommander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - api_network


networks:
  api_network:
    driver: bridge